version: '3'
services:
  redis-server:
    image: redis
    ports:
      - '6379:6379'
  visit-app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - redis-server
    restart: unless-stopped