version: "3"
services:
  react-test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

  react-web:
    build: ./Dockerfile.dev
      # context: .
      # dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - react-test